[build]
  command   = "npm run build"
  functions = "pages/api"
  publish   = "out"

[dev]
  functions = "pages/api"
  publish   = "out"
  # We manually set the framework to static, otherwise Netlify automatically
  # detects NextJS and redirects do not work.
  # Read more: https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#project-detection
  framework = "#static"

[[plugins]]
  package = "@netlify/plugin-nextjs"